from enum import Enum


class RelationshipTypes(Enum):
    SINGLE_RELATIONSHIP = 'SINGLE'
    AND_RELATIONSHIP = 'AND'
    OR_RELATIONSHIP = 'OR'


def SINGLE_RELATIONSHIP():
    return SINGLE_RELATIONSHIP


def AND_RELATIONSHIP():
    return AND_RELATIONSHIP

def OR_RELATIONSHIP():
    return OR_RELATIONSHIP